version: "2"

services:
  goaws:
    image: pafortin/goaws
    container_name: goaws
    ports:
      - 4100:4100

  app:
    image: pafortin/golang
    container_name: event_processor
    volumes:
      - ./:/go/src/event_processor/
    working_dir: /go/src/event_processor/cmd/
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    command: sh -c "fresh"
